"""initial

Revision ID: 489a376045f3
Revises:
Create Date: 2025-10-28 14:38:24.974644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "489a376045f3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analyses",
        sa.Column(
            "analysis_id",
            sa.String(length=26),
            server_default=sa.text("(ulid())"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("analysis_id"),
    )
    op.create_table(
        "project",
        sa.Column(
            "project_id",
            sa.String(length=26),
            server_default=sa.text("(ulid())"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "users",
        sa.Column(
            "user_id",
            sa.String(length=26),
            server_default=sa.text("(ulid())"),
            nullable=False,
        ),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("oidc_id", sa.String(length=255), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("full_name"),
        sa.UniqueConstraint("oidc_id"),
    )
    op.create_table(
        "transcriptions",
        sa.Column(
            "transcription_id",
            sa.String(length=26),
            server_default=sa.text("(ulid())"),
            nullable=False,
        ),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("text_output", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.project_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("transcription_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcriptions")
    op.drop_table("users")
    op.drop_table("project")
    op.drop_table("ai_analyses")
    # ### end Alembic commands ###
