"""add dismissed

Revision ID: 8156e810adf4
Revises: df22e93c0bbb
Create Date: 2025-11-13 09:36:18.030506

"""

from collections.abc import Sequence
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8156e810adf4"
down_revision: str | Sequence[str] | None = "df22e93c0bbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "dismissed_ai_analyses",
        sa.Column(
            "dismissed_analysis_id",
            sa.String(length=26),
            server_default=sa.text("(ulid())"),
            nullable=False,
        ),
        sa.Column("analysis_id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["ai_analyses.analysis_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("dismissed_analysis_id"),
    )
    op.add_column("ai_analyses", sa.Column("span", sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("ai_analyses", "span")
    op.drop_table("dismissed_ai_analyses")
